opposite_types = {"normal": ["fighting"],
                  "fighting": ["psychic", "flying", "fairy"],
                  "flying": ["electric", "ice", "rock"],
                  "poison": ["ground", "psychic"],
                  "ground": ["grass", "ice", "water"],
                  "rock": ["water", "grass", "fighting", "steel"],
                  "bug": ["flying", "rock", "fire"],
                  "ghost": ["psychic", "ghost", "dark"],
                  "steel": ["fighting", "fire", "ground"],
                  "fire": ["water", "rock", "ground"],
                  "water": ["electric", "grass"],
                  "electric": ["ground"],
                  "psychic": ["bug", "ghost", "dark"],
                  "ice": ["fighting", "rock", "fire", "steel"],
                  "dragon": ["ice", "dragon", "fairy"],
                  "fairy": ["poison", "steel"],
                  "dark": ["fighting", "bug", "fairy"],
                  "grass": ["fire", "flying"]
}